[nats]
broker-url = "localhost"
broker-port = 4222
username = ""
password = ""

[server]
name = "ft950"
index = 1

[input-device]
device-name = "default"
samplerate = 48000
latency = "5ms"
channels = 1
hostapi = "default"

[output-device]
device-name = "default"
samplerate = 48000
latency = "5ms"
channels = 2
hostapi = "default"

[opus]
application = "restricted_lowdelay"
bitrate = 24000
complexity = 5
max-bandwidth = "wideband"

[audio]
rx-buffer-length = 10 # 10x10ms (@framesize=480 & samplerate=48kHz)
# opus does not accept arbitrary frame length! Check OPUS documentation
frame-length = 480  #10ms @ 48kHz (should work for most cases)
tx-volume = 70
rx-volume = 70
stream-on-startup = false
vox = false
vox-threshold = 0.1
vox-holdtime = "500ms"

[http]
host = "localhost"
port = 9090