language: go
dist: trusty
sudo: true
matrix:
  include:
  - os: linux
    env:
    - GIMME_OS=linux
    - GIMME_ARCH=amd64
    go: '1.13'
  - os: osx
    env:
    - GIMME_OS=darwin
    - GIMME_ARCH=amd64
    go: '1.13'
cache:
  directories:
  - "$HOME/protobuf"
addons:
  apt:
    packages:
    - pkg-config
    - libsamplerate0
    - libsamplerate0-dev
    - libopusfile-dev
    - libopus-dev
    - libportaudio2
    - portaudio19-dev
    - autoconf automake libtool curl make g++ unzip
before_install:
- git fetch --tags
install:
- "./ci/install-deps-linux-osx.sh"
- export PATH=$PATH:$HOME/protobuf/bin
script:
- make dist
before_deploy:
- tar -cvzf remoteAudio-$TRAVIS_TAG-$GIMME_OS-$GIMME_ARCH.tar.gz remoteAudio
deploy:
  provider: releases
  api_key:
    secure: jNPrLOUIbmm47Nm9K/4D99ujlLfdUcHqGTx21FlJNYZwh4cjZiZV/txbVVn3r4Wd1JQJgp9PkWrSWIwxz/2Vov8cHfGsKHe1+13RezVrNUgEBQYNsBsvx5mBY/w7akoEADcEnsDOQGgXT7hc7eElSJDqo2VQRT7HRrbesSv15drrhTuujUdXl5JoMKL9A/4Xq83O4M5qW9w50bJ6siDwJL+ueUbr1cADxnUkY0UrBxl1gZIVN+r/xavzdTFSa+n3R6wvwjXQCDpMYotTjxIMC8DpAruCOyYz34EOpuT1Q82g+tHAQNZAyTHoxcuvVCpbK1FvSlXZ5XZCUFZOt4TEwnAjylt9mxxSUONDzzJ7CGQ3VgFY8ph7c4N+B+8U03A43UbsOv3kUrwwgQh59STTwk8ANM6NVVzrwdus0NDF3sDyN6lmcS8dhFCjlLD37HYjII8Jdl484ViBl5p1cpIcBB5mcc2gnfeU7iZwBTEesbn5zbGojaGlKwPJMYxPwl3R/mPZvuPxMxl8RCQhbvBNESi2uwztPi34O+uK0NbUC6dPrltlbYRyj8r7dPuntfrCsroAbg1KGQqTbMkI8fxV6aEZfsACYuYoQTEy5S3CERTQ7Ovpqu6FpivIDBlVrL+COnFD1vpMxtJzuAwve+QyWxpZ3lWI7JXdiUu2mCoai2g=
  file: remoteAudio-$TRAVIS_TAG-$GIMME_OS-$GIMME_ARCH.tar.gz
  skip_cleanup: true
  on:
    repo: dh1tw/remoteAudio
    tags:
      true
    draft: true
    go: "1.13"
